version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce:latest
    command: -H unix:///var/run/docker.sock --tlsskipverify
    ports:
      - "9443:9443"
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - towersfy_network # Use the existing network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager # Deploy only on manager node for simplicity
      restart_policy:
        condition: on-failure

volumes:
  portainer_data:

networks:
  towersfy_network:
    external: true # Reference the existing external network