services:
  postgres:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - towersfy_network
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_db_password
      - PG_MAX_CONNECTIONS=500
    secrets:
      - postgres_db_password
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M

secrets:
  postgres_db_password:
    external: true

volumes:
  postgres_data:
    external: true

networks:
  towersfy_network:
    external: true
