'use strict';
const {
  Model
} = require('sequelize');
module.exports = (sequelize, DataTypes) => {
  class RolePermissao extends Model {
    /**
     * Helper method for defining associations.
     * This file contains the associations automatically generated by Sequelize.
     * It is not necessary to define associations here if they are already defined
     * in the Role and Permissao models.
     */
    static associate(models) {
      RolePermissao.belongsTo(models.Role, { foreignKey: 'roleId', as: 'role' });
      RolePermissao.belongsTo(models.Permissao, { foreignKey: 'permissaoId', as: 'permissao' });
    }
  }
  RolePermissao.init({
    roleId: {
      type: DataTypes.UUID,
      allowNull: false,
      references: {
        model: 'roles',
        key: 'id',
      },
      onUpdate: 'CASCADE',
      onDelete: 'CASCADE',
    },
    permissaoId: {
      type: DataTypes.UUID,
      allowNull: false,
      references: {
        model: 'permissoes',
        key: 'id',
      },
      onUpdate: 'CASCADE',
      onDelete: 'CASCADE',
    },
  }, {
    sequelize,
    modelName: 'RolePermissao',
    tableName: 'role_permissoes', // Nome da tabela explícito
    timestamps: true,
    createdAt: 'createdAt',
    updatedAt: 'updatedAt',
    indexes: [
      {
        unique: true,
        fields: ['roleId', 'permissaoId']
      }
    ]
  });
  return RolePermissao;
};
